### ISSUE TITLE
no module hou

### ISSUE THREAD

**Issue by BlackRec** [shadeops/houdini-moana#2]
Hey :) Im pretty new to python and i try to enjoy the moana scene in houdini so I'm probably doing a mistake trying to unpack the scene with your tool.
So as i understand i need to open a cmd and dive into my folder island on my E drive so for that i do:

`e:`
`cd island`

then i do `python build_scene.py`

and i get this error: 
```
E:\3D\island>python build_scene.py
Traceback (most recent call last):
  File "E:\3D\island\build_scene.py", line 19, in <module>
    import hou
ModuleNotFoundError: No module named 'hou'
```

I'm probably doing something wrong but I'm sure it can help noob like me :)

**Comment by BlackRec** [comment]
I understand that I had to use houdini 17.5 to make the import of the digital asset working for the "VOP Disney material".
I can access this node without a problem after I execute the program.

To launch the script I open houdini 17.5, go to Windows, Python SHell and write this command `execfile('E:/3D/island/build_scene.py')`

I get this message : 
```
>>> execfile('E:/3D/island/build_scene.py')
00:40:31 Loading moana.hda
00:40:31 Building Json Cameras
00:40:31 Building Json Lights
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "E:/3D/island/build_scene.py", line 719, in <module>
    main()
  File "E:/3D/island/build_scene.py", line 715, in main
    post_scene_prep()
  File "E:/3D/island/build_scene.py", line 676, in post_scene_prep
    hou.node('/obj/osOcean').parm('vm_rendersubd').set(False)
AttributeError: 'NoneType' object has no attribute 'parm'
```
Im getting somewhere but I still need help haha !
